"""PII-detector training: corpus generation + fine-tuning job management.

The corpus is generated by templating real Synthea synthetic field values into natural
member utterances — because we inject each value ourselves, the character-span labels come
for free (no hand-labeling). See internal/phase-3-plan.md.
"""
